#!/bin/sh

if [ "$#" -lt 3 ]
then
	printf "usage: $0 run arch [docker args]\n"
	exit 1
fi

if [ $1 != "run" ]
then
	printf "first argument must be run\n"
	exit 1
fi

shift

ARCH=$1

shift

if [ ! -f qemu ]
then
	mkdir -p qemu
	(cd qemu && docker run justincormack/debian-qemu-user tarup.sh | tar xf -)
fi

if [ ! -f qemu/qemu-$ARCH-static ]
then
	printf "architecture $ARCH not found\n"
	exit 1
fi

docker info | grep -q 'Server Version: 1.10' && EXTRA_ARGS="--security-opt seccomp:unconfined"

# Parsing is rather flaky here, it needs to understand docker arguments

for var in "$@"
do
	if [ -z "$IMAGE" ] && echo "$var" | grep -q '^-'
	then
		EXTRA_ARGS="$EXTRA_ARGS $var"
	else
		if [ -z "$IMAGE" ]
		then
			IMAGE="$var"
		else
			ARGS="$ARGS $var"
		fi
	fi
done

#set -x

docker run --cap-add sys_admin -v $PWD/qemu/qemu-$ARCH-static:/usr/bin/qemu-$ARCH-static -v $PWD/run.sh:/usr/local/bin/run.sh $EXTRA_ARGS $IMAGE run.sh $ARGS
